# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filippofantinato/Desktop/FBK/simple-safety-synth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filippofantinato/Desktop/FBK/simple-safety-synth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filippofantinato/Desktop/FBK/simple-safety-synth/CMakeFiles /home/filippofantinato/Desktop/FBK/simple-safety-synth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filippofantinato/Desktop/FBK/simple-safety-synth/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple-safety-synth.out

# Build rule for target.
simple-safety-synth.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-safety-synth.out
.PHONY : simple-safety-synth.out

# fast build rule for target.
simple-safety-synth.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/build
.PHONY : simple-safety-synth.out/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/main.cpp.s
.PHONY : main.cpp.s

safety-arena/SafetyArena.o: safety-arena/SafetyArena.cpp.o
.PHONY : safety-arena/SafetyArena.o

# target to build an object file
safety-arena/SafetyArena.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-arena/SafetyArena.cpp.o
.PHONY : safety-arena/SafetyArena.cpp.o

safety-arena/SafetyArena.i: safety-arena/SafetyArena.cpp.i
.PHONY : safety-arena/SafetyArena.i

# target to preprocess a source file
safety-arena/SafetyArena.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-arena/SafetyArena.cpp.i
.PHONY : safety-arena/SafetyArena.cpp.i

safety-arena/SafetyArena.s: safety-arena/SafetyArena.cpp.s
.PHONY : safety-arena/SafetyArena.s

# target to generate assembly for a file
safety-arena/SafetyArena.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-arena/SafetyArena.cpp.s
.PHONY : safety-arena/SafetyArena.cpp.s

safety-solver/BDD2Aiger.o: safety-solver/BDD2Aiger.cpp.o
.PHONY : safety-solver/BDD2Aiger.o

# target to build an object file
safety-solver/BDD2Aiger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-solver/BDD2Aiger.cpp.o
.PHONY : safety-solver/BDD2Aiger.cpp.o

safety-solver/BDD2Aiger.i: safety-solver/BDD2Aiger.cpp.i
.PHONY : safety-solver/BDD2Aiger.i

# target to preprocess a source file
safety-solver/BDD2Aiger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-solver/BDD2Aiger.cpp.i
.PHONY : safety-solver/BDD2Aiger.cpp.i

safety-solver/BDD2Aiger.s: safety-solver/BDD2Aiger.cpp.s
.PHONY : safety-solver/BDD2Aiger.s

# target to generate assembly for a file
safety-solver/BDD2Aiger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-solver/BDD2Aiger.cpp.s
.PHONY : safety-solver/BDD2Aiger.cpp.s

safety-solver/SafetySolver.o: safety-solver/SafetySolver.cpp.o
.PHONY : safety-solver/SafetySolver.o

# target to build an object file
safety-solver/SafetySolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-solver/SafetySolver.cpp.o
.PHONY : safety-solver/SafetySolver.cpp.o

safety-solver/SafetySolver.i: safety-solver/SafetySolver.cpp.i
.PHONY : safety-solver/SafetySolver.i

# target to preprocess a source file
safety-solver/SafetySolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-solver/SafetySolver.cpp.i
.PHONY : safety-solver/SafetySolver.cpp.i

safety-solver/SafetySolver.s: safety-solver/SafetySolver.cpp.s
.PHONY : safety-solver/SafetySolver.s

# target to generate assembly for a file
safety-solver/SafetySolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/safety-solver/SafetySolver.cpp.s
.PHONY : safety-solver/SafetySolver.cpp.s

utils/aiger-utils.o: utils/aiger-utils.cpp.o
.PHONY : utils/aiger-utils.o

# target to build an object file
utils/aiger-utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/utils/aiger-utils.cpp.o
.PHONY : utils/aiger-utils.cpp.o

utils/aiger-utils.i: utils/aiger-utils.cpp.i
.PHONY : utils/aiger-utils.i

# target to preprocess a source file
utils/aiger-utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/utils/aiger-utils.cpp.i
.PHONY : utils/aiger-utils.cpp.i

utils/aiger-utils.s: utils/aiger-utils.cpp.s
.PHONY : utils/aiger-utils.s

# target to generate assembly for a file
utils/aiger-utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-safety-synth.out.dir/build.make CMakeFiles/simple-safety-synth.out.dir/utils/aiger-utils.cpp.s
.PHONY : utils/aiger-utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simple-safety-synth.out"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... safety-arena/SafetyArena.o"
	@echo "... safety-arena/SafetyArena.i"
	@echo "... safety-arena/SafetyArena.s"
	@echo "... safety-solver/BDD2Aiger.o"
	@echo "... safety-solver/BDD2Aiger.i"
	@echo "... safety-solver/BDD2Aiger.s"
	@echo "... safety-solver/SafetySolver.o"
	@echo "... safety-solver/SafetySolver.i"
	@echo "... safety-solver/SafetySolver.s"
	@echo "... utils/aiger-utils.o"
	@echo "... utils/aiger-utils.i"
	@echo "... utils/aiger-utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

